parameters:
#    modulo_residentes.example.class: AngelesVida\ModuloResidentesBundle\Example

services:
#    modulo_residentes.example:
#        class: %modulo_residentes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
