<?php

namespace Proxies\__CG__\AngelesVida\DataBaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articulo extends \AngelesVida\DataBaseBundle\Entity\Articulo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'codArticulo', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'descripcion', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'documento', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'nombre', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'compartir', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'tipoArchivo', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'link');
        }

        return array('__isInitialized__', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'codArticulo', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'descripcion', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'documento', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'nombre', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'compartir', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'tipoArchivo', '' . "\0" . 'AngelesVida\\DataBaseBundle\\Entity\\Articulo' . "\0" . 'link');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Articulo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodArticulo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodArticulo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodArticulo', array());

        return parent::getCodArticulo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', array());

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompartir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompartir', array());

        return parent::getCompartir();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoArchivo', array());

        return parent::getTipoArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', array());

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodArticulo($codArticulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodArticulo', array($codArticulo));

        return parent::setCodArticulo($codArticulo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', array($documento));

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function setCompartir($compartir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompartir', array($compartir));

        return parent::setCompartir($compartir);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoArchivo($tipoArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoArchivo', array($tipoArchivo));

        return parent::setTipoArchivo($tipoArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', array($link));

        return parent::setLink($link);
    }

}
