parameters:
#    modulo_internos.example.class: AngelesVida\ModuloInternosBundle\Example

services:
#    modulo_internos.example:
#        class: %modulo_internos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
